### ISSUE TITLE
Twitch oauth error

### ISSUE THREAD

**Issue by Wikotikabesa** [shughes-uk/physical_twitch_notifications#1]
Hi,
ive installed Python and phue/pyserial/pyyaml/twitchchat/twitchevents/webcolors.
Now i get an  [ErrorMSG](http://imgur.com/pqI0Q90) when i start the ptn.py 
In the config file i tryed:
twitch_oauth : "oauth:eee999ee9e9e9ee9ee"   and without "oauth:"   twitch_oauth : "eee999ee9e9e9ee9ee"

Any idears? 
This would be awesome when it works.

PS: I am not at home, so the Philips Bridge is not in the network atm.

**Comment by Wikotikabesa** [comment]
Now ive added "twitch_chat_oauth: "oauth:eee999ee9e9e9ee9ee"" in the config.txt. 
Now i get [this error](http://imgur.com/a/8JaYQ)

**Comment by shughes-uk** [comment]
I updated config_example.txt and pushed a fix for this. I guess I forgot to update this app when they started requiring client-ids for api requests. check the new config_example for how to get a client_id

**Comment by Wikotikabesa** [comment]
First of all i have to say thank u a lot.
I have create my TwitchApp, get the Client ID and fill it in the config.txt. Edited Twitchuser and Twitchchannel just for the [screenshot](http://imgur.com/a/Vjv40).
I think now ive done anything wrong.

**Comment by shughes-uk** [comment]
you will have to use a valid username and twitch channel, that error message is because you used a channel/username that doesn't exist

**Comment by Wikotikabesa** [comment]
Error again. That is my Twitch channel & user. Tryed channel with/without "#". Same Error.
Get a new oauth Token. Same Error
[Screenshot](http://imgur.com/a/H6ZLE)

**Comment by shughes-uk** [comment]
I will have to have a look at this in a couple of days

**Comment by Wikotikabesa** [comment]
I think [this can help](http://stackoverflow.com/questions/8840303/urllib2-http-error-400-bad-request) you.
Thx for your time, i will wait. Beleve u can fix it :)

**Comment by Wikotikabesa** [comment]
This is just a friendly reminder. ;)

**Comment by shughes-uk** [comment]
Hey It works for me so I suspect you have a misconfiguration, make sure your config file looks like this
```
twitch_username : "your_username_no_hashes"  # Twitch.TV username for the bot, must be a registered username!

twitch_chat_oauth : "oauth:adsadas"  # OAuth for above Twitch.TV account, http://www.twitchapps.com/tmi/

twitch_channel : "your_channel_name_no_hash"  # Twitch.TV channel to connect to

twitch_client_id : "your_client_id" # https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843
```

The double quotes around all the values are important

The 400 bad request seems to specifically come from having your client_id wrong, note it is different from your oauth!

**Comment by Wikotikabesa** [comment]
well...  get a new Client ID  Oauth etc..   I think this problem solved now. I dont know what ive done wrong.

[Still an Error](http://prntscr.com/fa4eso) 
Do u have a quick tip for me, otherwise i will try to fix it by my own. And thank u a lot for your support 👍 
I think the error says, that i have to find out, what IDs my lights have and configure it in the config.txt

**Comment by shughes-uk** [comment]
That is what it means yes, you can find your light names via the hue app.

**Comment by Wikotikabesa** [comment]
It was no problem to find the "type" and "hue_name" and it looks like it works well.
On a follower i got [another msg ](https://prnt.sc/fa55fs) (time out).
Google say thats becourse of a firewall. Turned off the firewall on that machine and Router, but this does not help.
Any port forwarding required?

**Comment by shughes-uk** [comment]
Delete the kankun socket entry in the configuration, I assume you don't have one of those

**Comment by Wikotikabesa** [comment]
I delete


plug_1 :
    type : "kankun_plug_socket"
    quick_name : "disco_lights_1"
    ip : "192.168.1.254"
    subscriptions :
      on_subscriber :
        action :
          turn_on :
            duration : 30 #seconds
      on_follower :
        action :
          turn_on :
            duration : 10


Error
CRITICAL twitchevents : Not starting, no callbacks registered

Tryed to delete IP or change  "kankun_plug_socket" to "" not helps

**Comment by shughes-uk** [comment]
Your config should look like this 
```
twitch_username : "animaggus"  # Twitch.TV username for the bot, must be a registered username!

twitch_chat_oauth : "oauth:blah"  # OAuth for above Twitch.TV account, http://www.twitchapps.com/tmi/

twitch_channel : "ryonday"  # Twitch.TV channel to connect to

twitch_client_id : "boooopu" # https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843
devices :
  lights_1 :
    type : "hue"
    hue_name : "your_hue_name"
    ip : "your hue bridge ip" # IP Address of the hue bridge
    subscriptions :
      on_start_streaming :
        action :
          flash :
            color_1 : "blue" #any colors from http://www.cssportal.com/css3-color-names/

            color_2 : "red" #any colors from http://www.cssportal.com/css3-color-names/

            times_to_flash : 15 #number of times to flash between the colors

            flash_speed : .2 #1 is slow but safe, 0.1 is very fast but is maybe cause odd behavior
      on_subscriber :
        action :
          flash :
            color_1 : "blue" #any colors from http://www.cssportal.com/css3-color-names/

            color_2 : "red" #any colors from http://www.cssportal.com/css3-color-names/

            times_to_flash : 15 #number of times to flash between the colors

            flash_speed : .01 #1 is slow but safe, 0.1 is very fast but is maybe cause odd behavior
      on_subscriber_count :
        count : 10
        triggered : false
        action :
          flash :
            color_1 : "green"

            color_2 : "pink"

            times_to_flash : 15

            flash_speed : .01
      on_follower :
        action :
          flash :
            color_1 : "red"
            color_2 : "blue"
            times_to_flash : 5
            flash_speed : 1
      on_follower_count :
        triggered : false
        count : 100
        action :
          flash :
            color_1 : "pink"
            color_2 : "green"
            times_to_flash : 5
            flash_speed : 1


```

**Comment by Wikotikabesa** [comment]
This is my config,

type: Is the Type of Lamp (Hue App)
hue_name: Is the name of the lamp, that i choose for the lamp in the App


---------------------
twitch_username : "animaggus"  # Twitch.TV username for the bot, must be a registered username!

twitch_chat_oauth : "oauth:blah"  # OAuth for above Twitch.TV account, http://www.twitchapps.com/tmi/

twitch_channel : "ryonday"  # Twitch.TV channel to connect to

twitch_client_id : "boooopu" # https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843
devices :
  lights_1 :
    type : "Hue color lamp"
    hue_name : "W_rgb2"
    ip : "192.168.0.23" # IP Address of the hue bridge
    subscriptions :
      on_start_streaming :
        action :
          flash :
            color_1 : "blue" #any colors from http://www.cssportal.com/css3-color-names/

            color_2 : "red" #any colors from http://www.cssportal.com/css3-color-names/

            times_to_flash : 15 #number of times to flash between the colors

            flash_speed : .2 #1 is slow but safe, 0.1 is very fast but is maybe cause odd behavior
      on_subscriber :
        action :
          flash :
            color_1 : "blue" #any colors from http://www.cssportal.com/css3-color-names/

            color_2 : "red" #any colors from http://www.cssportal.com/css3-color-names/

            times_to_flash : 15 #number of times to flash between the colors

            flash_speed : .01 #1 is slow but safe, 0.1 is very fast but is maybe cause odd behavior
      on_subscriber_count :
        count : 10
        triggered : false
        action :
          flash :
            color_1 : "green"

            color_2 : "pink"

            times_to_flash : 15

            flash_speed : .01
      on_follower :
        action :
          flash :
            color_1 : "red"
            color_2 : "blue"
            times_to_flash : 5
            flash_speed : 1
      on_follower_count :
        triggered : false
        count : 100
        action :
          flash :
            color_1 : "pink"
            color_2 : "green"
            times_to_flash : 5
            flash_speed : 1
-----------------
same as ur i think. Maybe i buy a *** Kankun Smart Wifi Plug for $27  :)

**Comment by shughes-uk** [comment]
Change your device type back to 'hue'

**Comment by Wikotikabesa** [comment]
lights_1 :
    type : "hue"
    hue_name : "W_rgb2"

[Then i get this error again. ](https://prnt.sc/fa6cfx)

**Comment by shughes-uk** [comment]
what is your hue light called in the app

**Comment by Wikotikabesa** [comment]
[W_rgb2](http://imgur.com/a/lWJVe)  Is the name that i have choose.
"Hue color lamp" is what the app say in the next line. That i cant change

**Comment by shughes-uk** [comment]
Not sure then, never used a color lamp. Only the light bulbs. You should talk to the maintainer of https://github.com/studioimaginaire/phue

**Comment by Wikotikabesa** [comment]
Okay, i will try this and link to this issue here.
Thank you for your help. I would certainly not have come so far.
All the best and much success continues.

**Comment by natcl** [comment]
Phue author here, seems like the 'name' property that arrives is W_rgb2 but there is the line
`if light.name.lower() == name:`
the name property is not lowered, I believe lowering name should solve the issue.

**Comment by Wikotikabesa** [comment]
thx for ur answer.  I have change the name in the hue app to "rgb2"
  lights_1 :
    type : "Hue color lamp"
    hue_name : "rgb2"

and ive test it with and without the  plug_1 in the code.
Without ive got again the msg when i run the ptn.py: CRITICAL twitchevents : Not starting, no callbacks registered
With the plug_1 the script starts currect and when i got an follower i [get this msg again](https://prnt.sc/fa55fs) :(

The rgb2 lamp does not react anytime

**Comment by Wikotikabesa** [comment]
lights_1 :
type : "hue"
hue_name : "rgb2"

The lamp does blink, jey :)
thx a lot. 
Now, I hope I'll get the rest by myself

**Comment by shughes-uk** [comment]
have fun!
